authorName: default
experimentName: example_mnist_pytorch
trialConcurrency: 1
maxExecDuration: 150h
maxTrialNum: 150
#choice: local, remote
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
assessor:
  #choice: Medianstop, Curvefitting
  builtinAssessorName: Curvefitting
  classArgs:
      epoch_num: 12
      start_step: 4
      threshold: 0.99
      gap: 1
trial:
  command: python3 train_seg_with_nni.py
  codeDir: .
  gpuNum: 1
localConfig:
  gpuIndices: 0,1,2,3
  useActiveGpu: True
  maxTrialNumPerGpu: 1
